packages:
  - examples/*
  - packages/background-only
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/testing-library
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/third-party/*
  - packages/tools/*
  - packages/use-sync-external-store
  - packages/web-platform/*
  - packages/webpack/*
  - packages/worklet-common
  - packages/motion-lynx
  - website
catalog:
  "@microsoft/api-extractor": 7.52.8
catalogs:
  rsbuild:
    "@rsbuild/core": 1.3.21
  rspack:
    "@rspack/cli": 1.3.15
    "@rspack/core": 1.3.15
    "@rspack/test-tools": 1.3.15
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - dprint
  - esbuild
overrides:
  "@rspack/core": catalog:rspack
  "@rsbuild/core>@rspack/core": catalog:rspack
  path-serializer: ^0.4.1
  motion: link:../../learn/motion/packages/motion
patchedDependencies:
  "@napi-rs/cli@2.18.4": patches/@napi-rs__cli@2.18.4.patch
  "@rollup/plugin-typescript": patches/@rollup__plugin-typescript.patch
